### ISSUE TITLE
fmp4

### ISSUE THREAD

**Issue by deepch** [widefire/websocketStreamServer#1]
fmp4 ready? I use it as dash?
What license?

**Comment by widefire** [comment]
This is a websocket streaming server for html5 live streaming, which transports rtmp streams to fmp4, and translates through websocket for progressive loading. It works with MSE(media source extension), and iOS doesn't support it for now, but lower latency on the other platforms than hls/dash. You can try it with playease.js  https://github.com/studease/playease      license apache 2.0

**Comment by deepch** [comment]
I have raw h264

(I connect ipcamera) sps, pps, i-frame, pframe
I can mux fmp4 and push it browser?
Perhaps you can tell me how to do it better using fmp4? it low latency?

I have hls , rtmp , rtsp need low latency html5 method delivery

**Comment by widefire** [comment]
the fmp4 is sliced by frame,so it's low latency.
you can know how to play fmp4 in html5 by read code playease.js 
you can just rtmp push h264 to the websocketstreamserver ,playease.js to play.or do it you self.

**Comment by deepch** [comment]
Maybe you can help me with this? I'm ready to freelancing
Contact me at admin@wetel.ru

**Comment by FgoDt** [comment]
We sent you an email, please check
